class ServiceFieldRules {
  static const Map<String, List<String>> disabledSituationsByField = {
    "dataAtendimentoEfetivo": ['Aguardando atendimento', 'Cancelado'],
    "valorServico": ['Aguardando atendimento', 'Cancelado', 'Sem defeito'],
    "valorPecas": ['Aguardando atendimento', 'Cancelado', 'Sem defeito'],
    "formaPagamento": [
      'Aguardando atendimento',
      'Cancelado',
      'Sem defeito',
      'Não aprovado pelo cliente',
      'Compra',
    ],
    "dataFechamento": [
      'Aguardando atendimento',
      'Aguardando aprovação do cliente',
      'Orçamento aprovado',
      'Aguardando cliente retirar',
      'Cortesia',
      'Garantia',
    ],
    "dataPagamentoComissao": [
      'Aguardando atendimento',
      'Sem defeito',
      'Aguardando aprovação do cliente',
      'Não aprovado pelo cliente',
      'Compra',
    ],
    "dataInicioGarantia": [
      'Aguardando atendimento',
      'Cancelado',
      'Sem defeito',
      'Aguardando aprovação do cliente',
      'Não aprovado pelo cliente',
      'Compra',
      'Orçamento aprovado',
      'Aguardando cliente retirar',
      'Não retira há 3 meses',
    ],
    "dataFinalGarantia": [
      'Aguardando atendimento',
      'Cancelado',
      'Sem defeito',
      'Aguardando aprovação do cliente',
      'Não aprovado pelo cliente',
      'Compra',
      'Orçamento aprovado',
      'Aguardando cliente retirar',
      'Não retira há 3 meses',
    ],
  };
}
