class ServiceFieldRules {
  static const Map<String, List<String>> disabledSituationsByField = {
    "nomeTecnico": ['Aguardando agendamento'],
    "horario": ['Aguardando agendamento'],
    "dataAtendimentoPrevisto": ['Aguardando agendamento'],
    "dataAtendimentoEfetivo": [
      'Aguardando agendamento',
      'Aguardando atendimento',
      'Cancelado',
    ],
    "valorServico": [
      'Aguardando agendamento',
      'Aguardando atendimento',
      'Cancelado',
      'Sem defeito',
    ],
    "valorPecas": [
      'Aguardando agendamento',
      'Aguardando atendimento',
      'Cancelado',
      'Sem defeito',
    ],
    "formaPagamento": [
      'Aguardando agendamento',
      'Aguardando atendimento',
      'Cancelado',
      'Sem defeito',
      'Não aprovado pelo cliente',
      'Compra',
    ],
    "dataFechamento": [
      'Aguardando agendamento',
      'Aguardando atendimento',
      'Aguardando aprovação do cliente',
      'Orçamento aprovado',
      'Aguardando cliente retirar',
      'Cortesia',
      'Garantia',
    ],
    "dataPagamentoComissao": [
      'Aguardando agendamento',
      'Aguardando atendimento',
      'Sem defeito',
      'Aguardando aprovação do cliente',
      'Não aprovado pelo cliente',
      'Compra',
    ],
    "dataInicioGarantia": [
      'Aguardando agendamento',
      'Aguardando atendimento',
      'Cancelado',
      'Sem defeito',
      'Aguardando aprovação do cliente',
      'Não aprovado pelo cliente',
      'Compra',
      'Orçamento aprovado',
      'Aguardando cliente retirar',
      'Não retira há 3 meses',
    ],
    "dataFinalGarantia": [
      'Aguardando agendamento',
      'Aguardando atendimento',
      'Cancelado',
      'Sem defeito',
      'Aguardando aprovação do cliente',
      'Não aprovado pelo cliente',
      'Compra',
      'Orçamento aprovado',
      'Aguardando cliente retirar',
      'Não retira há 3 meses',
    ],
  };
}
